services:
  postgres:
    image: postgres:18
    container_name: antec-postgres
    restart: unless-stopped

    environment:
      POSTGRES_DB: anteclms
      POSTGRES_USER: antec
      POSTGRES_PASSWORD: Antec123!

    ports:
      - "5432:5432"

    volumes:
      - postgres_data:/var/lib/postgresql

    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U antec -d anteclms"]
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  postgres_data:
